### ISSUE TITLE
User Story 1:

### ISSUE THREAD

**Issue by jonathanwhitedev** [jonathanwhitedev/love-running#1]
In order to **provide my opinion** with regards to a certain running topic or event as a **user**, I can **select and submit an answer from the poll.**

### Acceptance Criteria:

- The option to select a topic/event should have a comment box next to it
-  Upon clicking an opinion window should appear directly below the topic/event text
- A submit button should appear directly below this text window
- Confirmation to the user that a response has been submitted and include username 

### Tasks 

- [x] HTML/CSS to include an empty comment box underneath each topic/event
- [ ]  A submit button to appear after text has been entered using HTML/CSS 
- [ ] Controller to display confirmation to user
- [ ] Update test scripts
- [ ] Test the functionality

**Comment by jonathanwhitedev** [comment]
This is completed
